name: Asciidoc build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ hashFiles('**/*.gradle*') }}

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 11

    - name: graphviz install
      run: sudo apt-get install graphviz

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build
      run: ./gradlew asciidoc

    - name: Store release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        automatic_release_tag: "latest"
        title: "snapshot"
        draft: true
        files: |
          ${{ GITHUB_WORKSPACE }}/manual/build/distributions/manual.zip
          ${{ GITHUB_WORKSPACE }}/design/build/distributions/design.zip
          ${{ GITHUB_WORKSPACE }}/web/build/distributions/web.zip
          ${{ GITHUB_WORKSPACE }}/dsl/build/distributions/dsl.zip
          ${{ GITHUB_WORKSPACE }}/release-notes/build/distributions/release-notes.zip
        repo_token: "${{ secrets.GITHUB_TOKEN }}"